### ISSUE TITLE
Output of special characters in the Console

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/tesseract#10]
The console for this windows build (as well as the `cmd` in general) has problems to output special characters as Umlaute, e.g.

```
C:\Users\...\AppData\Local\Tesseract-OCR>tesseract -l frk 14339618.jpg -

dem K├╝n┼┐tler zu H├╝lfe. Die Freyhand - Zeichnungs-
kun┼┐t i┼┐t al┼┐o nur Mitgeh├╝lfin , aber nicht ┼┐chlechter-
dings nothwendige Mitarbeiterin der Pro┼┐pektive. Die ...
```

I tried to change the code page as described here https://www.heise.de/ct/hotline/Keine-Umlaute-auf-Kommandozeile-2055881.html but this didn't help. Any other suggestions or can this been even fixed in the console provided here in general?

**Comment by stweil** [comment]
Commit 9eb997fc0b5172d00507e7dcfeb2c68783d40190 might fix that. I'll create a new installer with that modification soon.

**Comment by zuphilip** [comment]
Yes, that is fixed now in the newest version `tesseract-ocr-w32-setup-v5.0.0-alpha.20190623`. Thank you!
