### ISSUE TITLE
trying to use this for trafic sign recog but empty text file

### ISSUE THREAD

**Issue by filipdns** [UB-Mannheim/tesseract#11]
hello, testing this, I success to decode image to text with screen shot of pc screen as source but using image from internet, the text file is empty.

what is wrong? too small? quality? what is restrictions?

![test](https://user-images.githubusercontent.com/35229046/56850654-c1483a80-6905-11e9-84f3-c09d54ae56b6.jpg)

![51561](https://user-images.githubusercontent.com/35229046/56850671-f6548d00-6905-11e9-8c5a-d5573c857787.png)

Thank you very much

**Comment by stweil** [comment]
The 1st image is recognized after some preprocessing (convert to high contrast b/w image) with `tesseract 56850654-c1483a80-6905-11e9-84f3-c09d54ae56b6.jpg - --psm 6`.

The 2nd image is recognized with `tesseract 56850671-f6548d00-6905-11e9-8c5a-d5573c857787.png - --psm 6`.

**Comment by stweil** [comment]
@filipdns, can this issue be closed?

**Comment by filipdns** [comment]
Oh sorry stweil, yes this solve the issue thank you very much
