### ISSUE TITLE
INPUT: a multipage TIFF file --> OUTPUT: text from only the first page

### ISSUE THREAD

**Issue by we1l** [UB-Mannheim/tesseract#12]
Hi, sorry that I am not providing any suggestions for fixing it but here is the issue I found:

INPUT: a TIFF file with multiple pages [sample TIFF](http://www.nightprogrammer.org/wp-uploads/2013/02/multipage_tiff_example.tif)
OUTPUT: only the first page gets OCR'ed
COMMAND: tesseract 1.tif 1.output

I have tried all options of --oem and --psm, but none worked.

Is this a limitation of this Windows version? Any comment is appreciated. Thanks a lot!

**Comment by stweil** [comment]
Support for multipage TIFF with embedded JPEG was only recently added to the Tesseract code. The latest installer uses that code, so maybe you want to give it a try and see whether it solves the problem.

**Comment by stweil** [comment]
@we1l, could you test a newer installer? Is this issue fixed?
