### ISSUE TITLE
Passing a list of image files does not work and provide output in hocr

### ISSUE THREAD

**Issue by FrkBo** [UB-Mannheim/tesseract#13]
### Environment

* **Tesseract Version**: 20190526
* **Commit Number**: N/A
* **Platform**: Windows 32 & 64 bit  

### Current Behavior:
if a list of image files is passed to Tesseract, it is unable to process the list. Windows throws an "tesseract has stopped working" error.

Also, when providing a filelist, the output cannot be set to hocr.

Example command: tesseract listoffiles.txt output -l eng
### Expected Behavior: 
Tesseract should process the provided list of images.
Note: tesseract 4.0.0-beta.3 does not have this issue and processes the same command correctly.

Both versions however are not able to produce hocr files when provided a filelist.

### Suggested Fix:
Unknown

**Comment by stweil** [comment]
Thank you for reporting this. I can reproduce this issue and will try to fix it.

**Comment by stweil** [comment]
What was the last installer which did not show this issue? I cannot find an installer for 4.0.0-beta.3.

**Comment by FrkBo** [comment]
Hi Stefan,

The version information shows the following:
[cid:53d04a40-8486-4c63-be18-8151bd57d8e9]

I suspect this version is downloaded from https://github.com/tdhintz/tesseract4win64
[https://avatars0.githubusercontent.com/u/10895586?s=400&v=4]<https://github.com/tdhintz/tesseract4win64>
tdhintz/tesseract4win64: charlesw/tesseract 4.0 build for x64 Windows using C++ run-time 141. - The world's leading software development platform · GitHub<https://github.com/tdhintz/tesseract4win64>
charlesw/tesseract 4.0 build for x64 and x86 Windows. This is a build of tesseract 4.0.0 beta, leptonica 1.77.0, and charlesw/tesseract .Net wrapper from September 10th sources. Tesseract 4.0.0 was built with OpenMP as follows ...
github.com
Regards,


Frank

________________________________
Van: Stefan Weil <notifications@github.com>
Verzonden: zondag 23 juni 2019 15:39
Aan: UB-Mannheim/tesseract
CC: FrkBo; Author
Onderwerp: Re: [UB-Mannheim/tesseract] Passing a list of image files does not work and provide output in hocr (#13)


What was the last installer which did not show this issue? I cannot find an installer for 4.0.0-beta.3.

**Comment by stweil** [comment]
I just released a new installer. My tests with it were successful. It also can create a hOCR file from a filelist.

**Comment by FrkBo** [comment]
Hi Stefan,

I can confirm the new installer works with filelists and hocr output! Thank you for time and effort in resolving this issue 🙂

Regards,

Frank

________________________________
Van: Stefan Weil <notifications@github.com>
Verzonden: zondag 23 juni 2019 19:46
Aan: UB-Mannheim/tesseract
CC: FrkBo; Author
Onderwerp: Re: [UB-Mannheim/tesseract] Passing a list of image files does not work and provide output in hocr (#13)


I just released a new installer. My tests with it were successful. It also can create a hOCR file from a filelist.
