### ISSUE TITLE
Recognize russian simbols

### ISSUE THREAD

**Issue by JonhSilver** [UB-Mannheim/tesseract#15]
Trying to recognize capcha like

![n](https://user-images.githubusercontent.com/24619483/60807600-c7bd2300-a18e-11e9-9704-82e81a81baaf.jpg)

tesseract.exe pic.jpg output -l rus

But captcha not recognized, how to recognize such capchas?

**Comment by stweil** [comment]
This is close to the optimum:

    tesseract 60807600-c7bd2300-a18e-11e9-9704-82e81a81baaf.jpg - -l tessdata_best/script/Cyrillic --psm 8
    } Бӱмба

Please use the [user forum ](https://github.com/tesseract-ocr/tesseract/wiki#support) for future questions.

**Comment by JonhSilver** [comment]
but what is tessdata_best/script/Cyrillic  ? i only have folder tessdata where is only two files eng.traineddata and rus.traineddata

**Comment by stweil** [comment]
https://github.com/tesseract-ocr/tessdata_best/blob/master/script/Cyrillic.traineddata
