### ISSUE TITLE
Wrong ftp filename

### ISSUE THREAD

**Issue by tropico2** [UB-Mannheim/tesseract#16]
### Environment
https://digi.bib.uni-mannheim.de/tesseract/

### Current Behavior:
tesseract-ocr-w32-setup-v4.1.0.20190314.exe contains tesseract v4.0.0.20190314, not v4.1.0.

### Suggested Fix:
Rename file accordingly.

**Comment by stweil** [comment]
The filename is correct, but the version, but the executables show a wrong version. I strongly suggest to use the latest version of the installer (5.0).
