### ISSUE TITLE
Version numbers

### ISSUE THREAD

**Issue by troplin** [UB-Mannheim/tesseract#17]
Tesseract published version 4.1.0 just a few days ago.
The version published here are 5.0.0-alpha and on the "older versions" page there's a version 4.1.0 from earlier this year (March). How do those versions relate?

Since the [official release 4.1.0 page](https://github.com/tesseract-ocr/tesseract/releases/tag/4.1.0) explicitly links here, it would be nice if that version was actually available.

**Comment by stweil** [comment]
I added a comment which explains our reasons to the [Wiki page](https://github.com/UB-Mannheim/tesseract/wiki). We recommend using 5.0.0-alpha. The older installers from March and May are based on release candidates of 4.1.0, so they don't differ much from the released 4.1.0.

**Comment by troplin** [comment]
Thanks for the clarifications, but I still find it a bit unfortunate TBH.
Version 5.0.0-alpha might be ok for the standalone tesseract commandline tool, but not so much for the API.
At least the 4.1.0 installers should be called RC on the download page.

Don't get me wrong, I appreciate the effort of providing windows installers. But the link from the release page make the installer somewhat official and not sticking to the official versioning leaves a bit of a bad taste.
The inconsistent versioning IMO makes it uncecessarily hard to integrate the engine into other products.
