### ISSUE TITLE
Installer under Win10 with Avast gives a malware alarm

### ISSUE THREAD

**Issue by JWBroekema** [UB-Mannheim/tesseract#18]
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below.

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by JWBroekema** [comment]
I try to install tesseract using the tesseract-ocr-w64-setup-v5.0.0-alpha.20190708.exe (64 bit) installer from UB-Mannheim under Win10 (1809).
Avast (engine 19.6.2383, version 19.6.4546.508; virus definitions 190721-0) warns for a FileRepMalware infection. The installer is moved to the virus vault.
I suppose this is a false positive but I cannot test this.

**Comment by stweil** [comment]
See [results from VirusTotal](https://www.virustotal.com/gui/url/078bc72c1b1f1305262b02c3080454d92fbd9e14571d817c0a0f06ad699ceb4d/detection).
