### ISSUE TITLE
Reported as a virus by Avast Antivirus

### ISSUE THREAD

**Issue by raffam** [UB-Mannheim/tesseract#19]
I have Windows 10 Educational edition. I also have Avast Antivirus 19.6.2383 (build 19.6.4546.511).
I have downloaded the binary for TesserAct 5.0.0 alpha, the 64 bit version, but Avast report it as a Virus, "FileRepMalware"

**Comment by raffam** [comment]
Now it reports it as another virus: IDP.Generic.f8a169aa8c85.3.2

**Comment by zuphilip** [comment]
See #18

**Comment by zuphilip** [comment]
@stweil Maybe filing out this formular https://www.avast.com/de-de/false-positive-file-form.php would help for people with Avast.

**Comment by stweil** [comment]
I have filed a report there now and close this issue. @raffam, https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v5.0.0-alpha.20190708.exe does not contain a virus (see the results from VirusTotal). Please check that your download was from our website, not from somewhere else.

**Comment by stweil** [comment]
Avast has just confirmed that they updated their database. It can take up to 24 hours until local scanners get the update.
