### ISSUE TITLE
Multi-threaded processing doesn't work

### ISSUE THREAD

**Issue by voodookoop** [UB-Mannheim/tesseract#22]
By default, tesseract.exe will do processing on 4 threads (if machine capable). OMP_THREAD_LIMIT=4 doesn't help when running from command line. It might be build specific.

**Comment by stweil** [comment]
I removed support for multithreading in the last binaries because it did not work well on Windows. See the comment "removed OpenMP" in the [Wiki](https://github.com/UB-Mannheim/tesseract/wiki).
