### ISSUE TITLE
Windows installer silent mode/command line or zip 

### ISSUE THREAD

**Issue by clauchiorean** [UB-Mannheim/tesseract#23]
### Environment

* **5+**: 
* **Windows 64-bit**: 

### Current Behavior:
The windows installer runs only in interactive mode
### Expected Behavior:
Run the installer also in silent mode
### Suggested Fix:
please provide an option to install from zip on windows

How can I ran the installer in silent mode?
I have a requirement to install tesseract on several windows machines with the possibility to update them in the feature.
I would like to find a way to run the windows installer in silent mode.

**Comment by stweil** [comment]
Both installer and uninstaller should also work in silent mode. Just run them with the command line parameter `/S`. It is also possible to specify the installation path using `/D=C:\Tesseract-5` for example. Getting language model would have to be done separately with other tools like `curl` or `wget`.

**Comment by stweil** [comment]
The installer was built with [NSIS](https://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System), so more information can be found [online](https://nsis.sourceforge.io/Docs/Chapter4.html#silent).

**Comment by AstralisSomnium** [comment]
@stweil @clauchiorean 
What are the arguments to select ALL additional script/language data, because by default they are disabled:

![image](https://user-images.githubusercontent.com/6730815/206896656-298425b3-40b4-4574-a7fb-d08bf63c7c9d.png)

**Comment by stweil** [comment]
There is no such argument. A possible solution was already mentioned above:

> Getting language model would have to be done separately with other tools like `curl` or `wget`.
