### ISSUE TITLE
Missing language data during installation: script/Laos and equ

### ISSUE THREAD

**Issue by chtof** [UB-Mannheim/tesseract#24]
### Environment

* **Tesseract Version**: 5.0.0-alpha.20191010
* **Platform**: Windows Version 1903 64 bits 

### Current Behavior:
When selecting "additional language data" and "additional script data" options in the installer, 2 popup errors are triggered during the installation:
- **Download error. Status of script/Laos. File Not Found (404). Click OK to continue.**
- **Download error. Status of equ. File Not Found (404). Click OK to continue.**

### Expected Behavior:
Successful installation of Tesseract when using "additional language data" and "additional script data" options.

### Suggested Fix:
Restore _script/Laos_ and _equ_ files or remove these languages from intaller options.

**Comment by stweil** [comment]
Thanks for reporting this. This will be fixed in the next installer. In the meantime you can get those models here:

- https://github.com/tesseract-ocr/tessdata/raw/master/equ.traineddata
- https://github.com/tesseract-ocr/tessdata_fast/raw/master/script/Lao.traineddata

**Comment by stweil** [comment]
`equ` should now work with old installers, too.

**Comment by chtof** [comment]
Thanks a lot @stweil , I will try to take these changes into account this week-end.

**Comment by stweil** [comment]
I think this issue was fixed, so I close it.
