### ISSUE TITLE
Win 64 libcurl-4.dll is missing

### ISSUE THREAD

**Issue by JohnLussmyer** [UB-Mannheim/tesseract#25]
### Environment

* **Tesseract Version**: 5.0.0-alpha
* **Commit Number**: 
* **Platform**: Win 7, 64 bit

### Current Behavior:
Unable to start, complains of missing libcurl-4.dll

### Expected Behavior:
starts

### Suggested Fix:
provide missing dll in win installer.

**Comment by stweil** [comment]
Thank you for reporting this. I replaced the installer with the same files plus the missing DLLs (libcurl-4.dll requires 3 more DLLs). The new Tesseract executable supports an image URL as input for the OCR.

**Comment by ChangePlaces** [comment]
I'm unable to pull an image from an url in either 64 or 32 bit, with a curl error that an assert failed in api/baseapi.cpp on line 1152. 

tesseract-ocr-w32-setup-v5.0.0-alpha.20191030.exe

**Comment by stweil** [comment]
Which image URL did you try? Or does it happen with any URL?

The assertion would be triggered by a bad URL or a dead link. The error handling code is still missing: it should print a user friendly message.

**Comment by ChangePlaces** [comment]
It happens with any URL, e.g. https://tesseract.projectnaptha.com/img/eng_bw.png

**Comment by stweil** [comment]
It happens with a https URL (try http://tesseract.projectnaptha.com/img/eng_bw.png). `curl_easy_perform` fails with error 60:

> CURLE_PEER_FAILED_VERIFICATION (60)
The remote server's SSL certificate or SSH md5 fingerprint was deemed not OK.

So the root certificates are missing or not found.

**Comment by stweil** [comment]
I still don't know where the root certificates are searched, so I am currently unable to fix the problem with https URLs. If someone finds a solution that would be welcome.

**Comment by ChangePlaces** [comment]
From memory, there may be an option to not verify ssl urls

**Comment by stweil** [comment]
Sure, but is that desirable? I don't think so. At least it should not be enabled by default. So perhaps adding a parameter which can disable the certificate verification might be a possible solution.

**Comment by stweil** [comment]
I close this issue because libcurl-4.dll is no longer missing. The latest version from today also reports curl errors instead of raising an assertion.
