### ISSUE TITLE
Can not run on winXP 64bit

### ISSUE THREAD

**Issue by ayajraynagnunug** [UB-Mannheim/tesseract#26]
### Environment

* **Tesseract Version**: tesseract-ocr-w64-setup-v5.0.0-alpha.20191030.exe
* **Commit Number**: 
* **Platform**: Windows XP Profesional Service Pack 1 - 64bit

### Current Behavior:
Can not run tesseract.exe
![Screen Shot 2019-11-15 at 9 33 05 PM](https://user-images.githubusercontent.com/57802933/68950840-8e0cc080-07ef-11ea-947c-122b292234ed.png)

### Expected Behavior:
Running well on Windows Xp 64 bit

**Comment by stweil** [comment]
Windows XP is end of life, so no longer supported by its vendor.

I suggest to use Tesseract on Linux which works well and is faster.

**Comment by stweil** [comment]
Building Tesseract for Windows XP is possible in principle, but needs some work. I estimate several days. So this is a question of priorities and costs.
