### ISSUE TITLE
Unattended install not available

### ISSUE THREAD

**Issue by jbarlow83** [UB-Mannheim/tesseract#27]
### Environment

* **Tesseract Version**: 5.0.0
* **Platform**: Windows 64

### Current Behavior:

Running the installer from a command line using an arguments still triggers the GUI. This means the installer can't be used in scripts like Chocolatey or unattended installs for continuous integration.

### Expected Behavior:

install.exe /?, /help should provide more details on how to run the installer in unattended mode.

### Suggested Fix:

Implement unattended or install or document it if it's already possible.

Thanks!

**Comment by stweil** [comment]
Unattended installs are possible with the standard options of NSIS installers and already used by Chocolatey.

**Comment by jbarlow83** [comment]
@stweil Thanks - I looked for the chocolatey package but couldn't find it, and now I found it... don't know why.
