### ISSUE TITLE
Win7 64 libgcc_s_seh-1.dll is missing

### ISSUE THREAD

**Issue by kajweb** [UB-Mannheim/tesseract#30]
### Environment

* **Tesseract Version**: 	tesseract-ocr-w64-setup-v5.0.0-alpha.20200205.exe
* **Platform**:  Win 7, 64 bit

### Current Behavior:
- Unable to start, complains of missing libgcc_s_seh-1.dll
- It work when I reInstall 	tesseract-ocr-w64-setup-v5.0.0.20190623.exe，

### Expected Behavior:
Nothing

### Suggested Fix:
add dll.

**Comment by stweil** [comment]
Thanks for reporting. The latest advertised version is [tesseract-ocr-w64-setup-v5.0.0-alpha.20191030](https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v5.0.0-alpha.20191030.exe).

**Comment by kajweb** [comment]
Thinks.I have uninstalled [tesseract-ocr-w64-setup-v5.0.0-alpha.20200205.exe](https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v5.0.0-alpha.20200205.exe) and reinstall the tesseract-ocr-w64-setup-v5.0.0-alpha.20191030.It work.

**Comment by stweil** [comment]
I just added a new version which should work, too.
