### ISSUE TITLE
Error message 0xc0000142

### ISSUE THREAD

**Issue by vivadavid** [UB-Mannheim/tesseract#31]
Tesseract Version: 5.0.0-alpha.20200223.
Platform: Windows 10 x64.
Hardware: Intel Core i7 (first generation) with Nvidia 230M.

PNG image in English. 
[image.zip](https://github.com/UB-Mannheim/tesseract/files/4333990/image.zip)

When I type this in the command line:

tesseract image.png output --oem 0 -l eng

I get the following error message (also when the value for --oem is 1, 2 or 3):

![2020-03-14 - 12 06 32 - Tesseract 5 (error message)](https://user-images.githubusercontent.com/9334287/76699063-dc50a400-66a9-11ea-83f1-399b7c39fdf7.png)

**Comment by stweil** [comment]
Which install directory do you use? Could you please change to that directory and run `tesseract --version` there?

**Comment by vivadavid** [comment]
@stweil, I installed Tesseract in a folder and kept all the files there: I didn't move anything.

If I run tesseract --version, I get the same error message.

**Comment by wtester7** [comment]
@stweil https://github.com/SubtitleEdit/subtitleedit/issues/3933#issuecomment-601137795

**Comment by stweil** [comment]
See also https://github.com/tesseract-ocr/tesseract/issues/2699.

**Comment by niksedk** [comment]
@stweil: So it's fixed in a later commit (after your tesseract v5.0.0 alpha.20200223 release) ?
Perhaps your commit: https://github.com/tesseract-ocr/tesseract/commit/ef4f99a9944525280baa64b5c2d72a1ad55ae8e8 ?

**Comment by stweil** [comment]
@niksedk, please try the latest installer from today which includes that commit.

**Comment by wtester7** [comment]
@niksedk and @stweil , yes the new version ( Tesseract 5.00 2020-03-28 Alpha ) is working well!
Thank you for the fix!!

**Comment by niksedk** [comment]
Thanks for the new build :)

**Comment by wtester7** [comment]
Btw, Tesseract 5.00 2020-03-28 Alpha is also much faster than 4.1.1! Thank you again!!

**Comment by vivadavid** [comment]
Working well now! Thanks, @stweil !
