### ISSUE TITLE
Signed executables possible for Windows?

### ISSUE THREAD

**Issue by ericswpark** [UB-Mannheim/tesseract#32]
Would signing the installers for Windows be possible? Right now it shows up as an unknown publisher and gets flagged by Windows SmartScreen. Thanks!

**Comment by stweil** [comment]
Signing Windows installers is not a technical problem, but requires a certificate which costs money if it is accepted by Microsoft. I could sign the executables with my free private certificate (like I do it for the [QEMU installers](https://qemu.weilnetz.de/)), but Windows SmartScreen would still complain.

**Comment by ideaman924** [comment]
Yup, I know that EV certificates are required. I know that some FOSS programs like Notepad++ get their EV certificates free from CAs through partnerships which is why I was wondering if the same would be possible for the tesseract installer.

**Comment by stweil** [comment]
Suggestions are welcome. I have no idea which CAs would be willing to give me a free certificate or how I could apply for such a partnership.

**Comment by stweil** [comment]
There are still no free code signing certificates available, and I also have no sponsor who would pay for a commercial certificate. So I close this issue.
