### ISSUE TITLE
The eng.traineddata provided by default is faulty.

### ISSUE THREAD

**Issue by piyushspss** [UB-Mannheim/tesseract#35]
### Suggested Fix: Please update the file.

**Comment by stweil** [comment]
The provided file is not faulty, but simply a model made for fast OCR, so fits for most users.

If you want to do OSD, either don't specify a language or - if you have to specify a language - get a traineddata file from https://github.com/tesseract-ocr/tessdata/.

**Comment by piyushspss** [comment]
I tried osd without specifying a language with passports and it was not giving me correct results. Please try once.

![tp3](https://user-images.githubusercontent.com/5053694/83137874-84053c00-a107-11ea-861a-55f42f7a0688.jpg)
![type3](https://user-images.githubusercontent.com/5053694/83137723-44d6eb00-a107-11ea-88db-d9cf1aa9809e.png)
![type2](https://user-images.githubusercontent.com/5053694/83137728-46a0ae80-a107-11ea-9235-b029bb5e26da.png)

**Comment by stweil** [comment]
Indeed. Then you have to get the right eng.traineddata.
