### ISSUE TITLE
Very much more thanks if you include tesseract4.lib in installer.

### ISSUE THREAD

**Issue by wowfoot** [UB-Mannheim/tesseract#4]
Thanks for windows installer.
Very much more thanks if you include tesseract4.lib in installer.

**Comment by stweil** [comment]
That library is not needed for users who only want to work with Tesseract.

If you want to develop own applications based on Tesseract, tesseract4.lib is not sufficient, because you also need the Tesseract API header files. For that I suggest to build Tesseract from source yourself.
