### ISSUE TITLE
tesseract orc with a company computer

### ISSUE THREAD

**Issue by jsutter25** [UB-Mannheim/tesseract#40]
Hello,

Congratulation for the post. The optical character recognition is very efficient !

I have a question : with my personal computer (Windows) the optical character recognition works very well using the tesseract-ocr-w64-setup-v5.0.0-alpha.20200328.exe file. However, as I am working in a pharmaceutical company I am using the computer of the company. It is not possible for me to install the tesseract-ocr-w64 (all the software or other installers are blocked by the computer). 

Do you think there is a solution ?

Thank you very much, and have a nice day,

Jean Alexandre Sutter

**Comment by stweil** [comment]
I suggest to ask your local IT for a solution. Working around rules for the computers of your company might not be a good idea, even if it is possible to install executables.

**Comment by jsutter25** [comment]
Thank you very much for your quick answer, I will see with the IT team.

Have a nice day !
