### ISSUE TITLE
4.1.1 w64 - icuuc56.dll missing from unicharset_extractor.exe

### ISSUE THREAD

**Issue by waylandc** [UB-Mannheim/tesseract#41]
### Environment

* **Tesseract Version**: 4.1.1
```shell
(ocr) C:\Users\Wayland\work\pywork\grogu\screenshots>tesseract --version
tesseract 4.1.1
 leptonica-1.78.0 (Sep 28 2020, 16:25:11) [MSC v.1916 LIB Release x64]
  libjpeg 9d : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libopenjp2 2.3.1
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.3.3 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.8.1 libzstd/1.3.7
```
* **Commit Number**: 
* **Platform**: 
Windows 10 64 bit

### Current Behavior:
Trying to use unicharset_extractor.exe to train something and I get missing icuuc56.dll error.

I read that the 5.x alpha branch is good for windows by I'm using tesserocr on python which requires 4.x

**Comment by stweil** [comment]
Thank you for reporting that problem.

I use `tesserocr` with Python 3 very often with latest Tesseract, so using 5.x should work fine.

**Comment by stweil** [comment]
I just checked our code and did not find a Tesseract `4.1.1` released for Windows by UB Mannheim. Nor do we use an `MSC` compiler like it is indicated in your version message for `leptonica`.

Where did you get the Windows binaries from?

**Comment by waylandc** [comment]
Hi @stweil thanks for noticing. Looks like I had 2 versions installed and the one I was using came from a conda installation.

I'm going to go ahead and try 5.x though.
