### ISSUE TITLE
Wrong installation folder for Windows 64 bits

### ISSUE THREAD

**Issue by Reznov** [UB-Mannheim/tesseract#5]
### Environment

* **Tesseract Version**: 4.0.0
* **Platform**: Windows 10 1809 x64

**Comment by stweil** [comment]
Did you install a 32 bit version before? Then the installation folder from that installation will be reused.

A fresh installation should use the right folder, see the [code](https://github.com/UB-Mannheim/tesseract/blob/windows/nsis/tesseract.nsi#L153).

You should also get the right folder if you uninstall any previous installations of Tesseract before installing a new 64 bit version.

**Comment by stweil** [comment]
Thank you. That was indeed a bug in the installer. It is fixed now with commit 399b5409ece6db10f2235567ce184def6ab31ba9 in release [v4.1.0.20190314](https://github.com/UB-Mannheim/tesseract/releases/tag/v4.1.0.20190314).
