### ISSUE TITLE
Cannot download tesseract for windows (v5)

### ISSUE THREAD

**Issue by MikeDuf** [UB-Mannheim/tesseract#50]
I get the 'connection timed out' issue.

**Comment by stweil** [comment]
Our server is currently down. Please try again later. Maybe you have to wait until Monday.

**Comment by MikeDuf** [comment]
Wow very fast answer. Big thank you. Cannot wait for tomorrow to try it out again.

**Comment by MikeDuf** [comment]
This morning (monday , 20-9-2021) it works. Thank you for your time.
