### ISSUE TITLE
unicharset_extractor.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by TustyBusty** [UB-Mannheim/tesseract#51]
------------------------

### Environment

* **Tesseract Version**: v5.0.0.20211201.exe (32 bit)
* **Commit Number**:
* **Platform**: Windows 10 64-bit
### Current Behavior:
when running unicharset_extractor.exe, Im met with the following error. 
![image](https://user-images.githubusercontent.com/95774545/145267854-cbd66763-44e6-4a35-b10f-e39d223ff2a9.png)

### Expected Behavior:
unicharset should be created successfully

**Comment by stweil** [comment]
I cannot reproduce that error.

As you are running on a 64-bit Windows, I suggest to try the 64-bit installer.
