### ISSUE TITLE
pip install tesseract

### ISSUE THREAD

**Issue by pdot6592** [UB-Mannheim/tesseract#53]
has any experienced this install issue?
### Suggested Fix:
![tesseract_issue](https://user-images.githubusercontent.com/68824709/149208348-56d24df0-b0e1-4b42-89a3-c12759d13432.PNG)

**Comment by stweil** [comment]
I don't know. Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
