### ISSUE TITLE
Unable to install 5.0.1 with additional language

### ISSUE THREAD

**Issue by jusla** [UB-Mannheim/tesseract#54]
### Environment

* **Tesseract Version**: 5.0.1 64-bit
* **Platform**: Windows 10 Enterprise version 21H2

### Current Behavior:

When installing 5.0.1, I selected Finnish as additional language. During the actual installation, I received the following error message shown in the screenshot:

Transcript of error message in case screenshot does not appear correctly:
![tesseractdownloaderror](https://user-images.githubusercontent.com/26478692/149276834-c4fb3583-4c2e-4536-ada5-ba3d66c752cd.png)

"Download error. Status of fin: [Asian language characters]. Click OK to continue."

Installation was completed, but Finnish language was not installed (I checked the tessdata folder).

The same behaviour occurred on another Windows 10 Home 21H2 computer when installing Tesseract 5.0.0 and 5.0.1.

I know that this is not a major issue as you can download and copy the languages manually from GitHub (and I did).

### Expected Behavior:

Finnish language is downloaded and installed when selected in installer.

### Suggested Fix:

-

**Comment by stweil** [comment]
Do other language downloads work? Or is the problem only with `fin`?

If all downloads fail, it might be caused by a network problem. I noticed that GitHub is blocked in some parts of the world.

**Comment by jusla** [comment]
I uninstalled and reinstalled Tesseract, this time selecting deu, fra and ita for download. The installer gave the same error message for each language.
This has worked for fin from Finland in previous Tesseract versions. Unfortunately I cannot pinpoint the version or time when it has stopped working (quite recently though).

**Comment by stweil** [comment]
Thank you. I can now reproduce the issue and will have a look what goes wrong.

**Comment by stweil** [comment]
The download function is broken since commit 19df20451230384545fd73688407f78d87c648f7 (2021-12-06).

NSIS suggests to enable unicode, but the [NSIS Inetc plugin](https://nsis.sourceforge.io/Inetc_plug-in) does not work when unicode is enabled. :-(

**Comment by stweil** [comment]
I could fix the download function, but there remains another new problem: the NSIS Inetc plugin tries to download using the HTTP protocol instead of HTTPS, but GitHub no longer supports HTTP downloads. Therefore the fixed installer still cannot download model files, but shows error `301 Moved Permanently` (the HTTP URL was moved to HTTPS).

Currently I have no solution how to enable HTTPS downloads. I could only duplicate the `tessdata_fast` repository on a server which allows HTTP downloads.

**Comment by stweil** [comment]
@jusla, please try the latest installers which should fix the issue. Model files are now downloaded from one of our servers which is configured to support HTTP downloads.

**Comment by jusla** [comment]
@stweil Sorry for not testing earlier! I must have missed the notification about your message. I tried the new installer tesseract-ocr-w64-setup-v5.0.1.20220118.exe and now the language download worked fine at least for fin and swe.
Thank you for fixing this!

**Comment by stweil** [comment]
So can we close the issue?

**Comment by jusla** [comment]
> So can we close the issue?

Yes. Thank you!
