### ISSUE TITLE
Error in pixReadStream

### ISSUE THREAD

**Issue by walter-weinmann** [UB-Mannheim/tesseract#56]
### Environment

* **Tesseract Version**: 

```
tesseract v5.0.0.20211201
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
 Found libarchive 3.5.0 zlib/1.2.11 liblzma/5.2.3 bz2lib/1.0.6 liblz4/1.7.5 libzstd/1.4.5
 Found libcurl/7.77.0-DEV Schannel zlib/1.2.11 zstd/1.4.5 libidn2/2.0.4 nghttp2/1.31.0
```

* **Commit Number**: 
* **Platform**: 

![image](https://user-images.githubusercontent.com/1956149/158398480-f36d0b18-fb0c-49da-bf63-440208c45b5e.png)

### Current Behavior:

`Error in pixReadMemBmp: cannot read compressed BMP files Error in pixReadStream: bmp: no pix returned Error in pixRead: pix not read Error during processing.`

The file is available [here](https://github.com/KonnexionsGmbH/dcr/blob/wwe_0.7.0/tests/__PYTEST_FILES__/all_example_files_tesseract/pdf_scanned_01_ok.bmp)

### Expected Behavior:

Converting bmp image to pdf file.

**Comment by stweil** [comment]
Please try whether that issue also occurs with the latest Tesseract for 'Windows. If possible try also Tesseract on Linux.

**Comment by walter-weinmann** [comment]
@stweil please see response here #57

**Comment by walter-weinmann** [comment]
I finally managed to install the latest version, but still the same problem:

`Error in pixReadMemBmp: cannot read compressed BMP files Error in pixReadStream: bmp: no pix returned Error in pixRead: pix not read Error during processing.
`

Since this also occurs on Ubuntu - I'll close the issue and go to Tesseract OCR directly.
