### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by sbcel123** [UB-Mannheim/tesseract#6]
tesseract-4.0.0
OS:suse 11sp4

li19fieapdf00:/opt/software/tesseract4.0/tesseract-4.0.0 # ./autogen.sh
Running aclocal
configure.ac:490: warning: macro `AM_COND_IF' not found in library
configure.ac:503: warning: macro `AM_COND_IF' not found in library
configure.ac:516: warning: macro `AM_COND_IF' not found in library
Running /usr/bin/libtoolize
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
libtoolize: copying file `config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
Running autoheader
Running automake --add-missing --copy
configure.ac:82: installing `config/config.guess'
configure.ac:82: installing `config/config.sub'
configure.ac:23: installing `config/install-sh'
configure.ac:23: installing `config/missing'
src/api/Makefile.am: installing `config/depcomp'
unittest/Makefile.am:248: variable `EXTRA_apiexample_test_DEPENDENCIES' is defined but no program or
unittest/Makefile.am:248: library has `EXTRA_apiexample_test' as canonic name (possible typo)
Running autoconf
configure.ac:10: error: possibly undefined macro: m4_esyscmd_s
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:465: error: possibly undefined macro: AC_CONFIG_FILES
configure.ac:493: error: possibly undefined macro: AM_COND_IF

  Something went wrong, bailing out!

**Comment by stweil** [comment]
Please use the Tesseract binaries which are available for SuSE.
