### ISSUE TITLE
New versions

### ISSUE THREAD

**Issue by Lambdac0re** [UB-Mannheim/tesseract#60]
Will there be continued builds? (Version 5.10 for example)
Thanks so much!

**Comment by stweil** [comment]
Yes. Are there special features from 5.1.0 which you are missing?

**Comment by Lambdac0re** [comment]
I have issues with some files and I do not know if they can be resolved with a new version of tesseract/leptonica.

**Comment by stweil** [comment]
Meanwhile there is a new version available. Maybe you want to try it.
