### ISSUE TITLE
Can't even run or start on Windows 10

### ISSUE THREAD

**Issue by AngelTs** [UB-Mannheim/tesseract#65]
tesseract-ocr-w32-setup-5.3.0.20221222.exe:
The application was unable to start correctly (0x000007b). Click OK to close the application).

tesseract-ocr-w64-setup-5.3.0.20221222.exe:
The application was unable to start correctly (0x000007b). Click OK to close the application).

Windows 10 Pro, 22H2, 19045.2604

**Comment by AngelTs** [comment]
But the the following versions start normal:
-tesseract-ocr-w64-setup-v5.0.0.20211201.exe
-tesseract-ocr-w64-setup-v5.0.1.20220118.exe
-tesseract-ocr-w64-setup-v5.1.0.20220510.exe
-tesseract-ocr-w64-setup-v5.2.0.20220712.exe
So, the problem is the last version- tesseract-ocr-w64-setup-5.3.0.20221222.exe?

**Comment by stweil** [comment]
Please try the next installer for release 5.3.1 which will be available tomorrow.
