### ISSUE TITLE
Silent install destination folder and languages to be installed

### ISSUE THREAD

**Issue by agonzalezm** [UB-Mannheim/tesseract#66]
I am installing using windows silent installer option /S is there any way to specify destination folder and languages to install?

I tried  /D=$INSTDIR\..\My-OCR  or /D=C:\MyOCR but it didnt work

**Comment by stweil** [comment]
See [documentation for NSIS installers](https://nsis.sourceforge.io/Which_command_line_parameters_can_be_used_to_configure_installers%3F).

I don't know a way how to specify the languages and scripts to install silently, but model files can be installed separately by downloading them from GitHub or other sources.
