### ISSUE TITLE
32bit version fails to launch

### ISSUE THREAD

**Issue by CanadianHusky** [UB-Mannheim/tesseract#7]
Hello,

I have tested 2 seperate 32bit systems now. One of them never had any tesseract installation and is completely 'clean'. The result was the same error. 
Installation seems successfull without any error messages

I am using 32bit windows installer from
https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w32-setup-v4.0.0.20181030.exe

I have uninstalled and reinstalled vc_redist_86.exe for VS 2008, 2010, 2012, 2013, 2015 each with the latest available update hoping to find the right runtime by trial and error but the exe still cannot be launched.

![image](https://user-images.githubusercontent.com/35332003/50333984-f38cfa00-0517-11e9-8468-af3e056b4c5a.png)

what am I doing wrong ?
thank you

**Comment by stweil** [comment]
It works for me with [msvcrt.dll 7.0.7601.17744](https://digi.bib.uni-mannheim.de/tesseract/msvcrt.dll). Please try again with that file in the same folder as `tesseract.exe`.

**Comment by stweil** [comment]
See also duplicate at https://github.com/tesseract-ocr/tesseract/issues/2131.

**Comment by CanadianHusky** [comment]
unfortunately still the same when placing in same folder

![image](https://user-images.githubusercontent.com/35332003/50337559-8c287780-0522-11e9-9489-6a4952d37dc7.png)

I also tried deleting and overwriting C:\windows\system32\msvcrt.dll and replace the version there with the file you provided but windows *hates* that and find a secretly cached version from somewhere and replace the file back to the original right away

**Comment by stweil** [comment]
Maybe `msvcrt.dll` requires some other DLL which is missing on your system. I'd use a dependency tracker to find out which one. You could also try to start `tesseract.exe` by double-clicking from the Windows explorer. Maybe that gives a better diagnostic message.

**Comment by CanadianHusky** [comment]
Thank you for the tips. Starting with Windows explorer results in the same message
On the same station with the error message, installing this version works and tesseract launches fine.
I tested all versions backwards until I found which version is the last working version.
I can live with that version for 32bit machines. 'Serious' users have 64bit machines anyways.

tesseract-ocr-setup-4.0.0-alpha.20180109.exe

I am pretty sure something in the compile process or the underlying libraries changed between that date and the next release.
thanks for the suggestions

**Comment by stweil** [comment]
`_splitpath_s` was first used in April 2018 (see commit d88a6b5c1992d13ada92750407438175ae425533), so all older versions did not require it.

**Comment by stweil** [comment]
Could you please try again with the latest release?

**Comment by CanadianHusky** [comment]
Of course.

My first test on a windows xp 32 bit station failed with the same message. However I do not trust that result at the moment because I played a lot on that station with msvcrt.dll in order to find a working version with trial and error. I had unregistered and re-registered DLLs a lot. Out of the box it does not work on that station. 

I have asked my collegues to test on 3 other 32bit "clean" stations, windows 7 32bit and windows xp 32bit and will report the results as soon as I have them.

When I install the 32bit installer from 
https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w32-setup-v4.1.0.20190314.exe

on Windows 7, 64bit the result is fine
![image](https://user-images.githubusercontent.com/35332003/54421733-1cd7b380-471e-11e9-80ba-c64b9579ec76.png)

just the version string seems to still say 4.0.0 instead of 4.1.0

thank you

**Comment by stweil** [comment]
Thanks. I already noted the wrong version string. That was caused by my build process which did not run `./autogen.sh`.

**Comment by CanadianHusky** [comment]
all 32bit stations (Windows XP) that I had tested the 20190314 release on fail with the same error
3 seperate stations were tested
These were pristine and clean installs with very little other software installed

the 32bit installer files work fine on 64 bit stations windows 7 and above

**Comment by stweil** [comment]
I am afraid that [`_splitpath_s`](https://docs.microsoft.com/de-de/cpp/c-runtime-library/reference/splitpath-s-wsplitpath-s?view=vs-2017) might be unsupported for Windows XP, but could not find more information online.

**Comment by CanadianHusky** [comment]
Understood.

Further question in my mind

What is **_splitpath_s** used for now, starting in April 2018, when it was not needed up until then ?
can it not be replaced with a self written function that does the same ?
It seems like a simple direcorty/path seperating function with a few additonal checks

I don't think it is a critical component of the actual recognition code, seems just like a helper function but the decision is of course for the developer team.

**Comment by stweil** [comment]
It isn't a critical component, so yes, that small part of the code can be replaced. Done in [this new 32 bit installer](https://digi.bib.uni-mannheim.de/~stweil/tesseract-ocr-w32-setup-5.0.0-alpha-162-ge1525087.exe). Do you want to try whether it works on Windows XP?

**Comment by CanadianHusky** [comment]
The supplied exe installs and runs fine on Windows XP. It does regular OCR detection fine as well, thank you very much.

however there are a few strange problems, unrelated to the compiler issue 

1- accuracy problem mentioned in this issue

https://github.com/tesseract-ocr/tesseract/issues/2062

still exists, no matter what command line options I tried.

2- there are new inconsistent font error messages, which do not make sense. I am not sure if new bugs got introduced or not

Please see sequence of commands below and my explanation, or move this post to another suitable thread

![image](https://user-images.githubusercontent.com/35332003/58483466-09f34d80-8169-11e9-8b3a-569e13133d70.png)

![image](https://user-images.githubusercontent.com/35332003/58483603-42932700-8169-11e9-9f33-10ffb216c123.png)

without -l  code runs, output orientation for sample image is wrong
with -l osd code runs, output orientation for sample image is wrong
with -l eng code fails, despite eng being reported as an installed file

I do not understand the behaviour and since this binary is compiled from the latest source, I am concerned the same problem exists in the future version

```
Page number: 0
Orientation in degrees: 180
Rotate: 180
Orientation confidence: 0.36
Script: Latin
Script confidence: 4.67

```

input.png for reference. 
No setting I tested could detect 0 orientation with a meaningfull accuracy on this image

![input](https://user-images.githubusercontent.com/35332003/58483970-dc5ad400-8169-11e9-8fde-211f4a0931a5.png)

**Comment by stweil** [comment]
Thank you for testing and reporting the results. I'll look for those new issues.

**Comment by stweil** [comment]
Tesseract cannot load `eng.traineddata` because that file exists, but does not include the legacy model which you requested by `--oem 0`. Either omit that option or install `eng.traineddata` from https://github.com/tesseract-ocr/tessdata. That also detects the right orientation.

**Comment by stweil** [comment]
@CanadianHusky, is there anything still open, or can this issue be closed?

**Comment by CanadianHusky** [comment]
@stweil,
I have upgraded all stations that use this to x64 and version 5.0.0. alpha 20201127. I am sorry I do not have a 32bit station to Test anymore.

On a side note, version 5.0.0. 20201127 seems to have a performance improvement of around 250% for full page text recognition for DIN A4 text pages compared to version 4.1.0. for content that I work with. I hope that performance can be maintained as new features are added and the alpha release turns stable.
Brilliant work, thanks to the Team that worked on this.
