### ISSUE TITLE
Link fo file download not found. (404 error) (https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-5.3.1.20230401.exe)

### ISSUE THREAD

**Issue by carlosfalcone** [UB-Mannheim/tesseract#70]

**Comment by stweil** [comment]
It works for me.

**Comment by Hermann12** [comment]
Link works for me too.

**Comment by carlosfalcone** [comment]
Today the link is working.
Thanks for your reply.

Em dom., 30 de abr. de 2023 às 02:01, Hermann12 ***@***.***>
escreveu:

**Comment by Anime37** [comment]
Had the same issue. Making my DNS automatic instead of Manual solved the problem.

**Comment by kaixxx** [comment]
I had the same problem. Might have to do with the cookie policy.  After I visited https://digi.bib.uni-mannheim.de/ and answered to the cookie question (I denied cookies), the download links worked fine.

**Comment by stweil** [comment]
The download link does not use any cookies. I think there is a DNS problem if downloads fail. Usually a retry (maybe later) should help.

**Comment by anphex** [comment]
It's an on-off-behaviour guys. I tried some python experiments on multiple machines and it was hit or miss. 
If an university in one of the most developed countries in the world isn't capable of running a basic website, that's all you need to know about IT progress in Germany.

**Comment by stweil** [comment]
@anphex, a more detailed bug report would be helpful. The web server is up more than 99.9% of the time, only restarted when necessary due to a new Linux kernel. What exactly is failing? Are you getting timeouts? Is name resolution failing?

**Comment by anphex** [comment]
> @anphex, a more detailed bug report would be helpful. The web server is up more than 99.9% of the time, only restarted when necessary due to a new Linux kernel. What exactly is failing? Are you getting timeouts? Is name resolution failing? From which part of the world are downloads failing?

Good morning! I was really annoyed yesterday because installing the tesseract exe was one of the last parts of finishing a script and it was already late. Sorry for my mean comment. The only thing I can "confirm" through my chrome history is that there was no connection possible at 22:25 German time.

**Comment by damies13** [comment]
@stweil 

If it helps, I can give date/times when it failed to download in my build process vs when it download successfully

Times when file download failed:
- Fri, 18 Aug 2023 12:08:14 GMT - https://github.com/damies13/rfswarm/actions/runs/5902381849/job/16010313120
- Fri, 18 Aug 2023 12:06:30 GMT - https://github.com/damies13/rfswarm/actions/runs/5902381849/job/16010313287
- Fri, 18 Aug 2023 12:06:38 GMT - https://github.com/damies13/rfswarm/actions/runs/5902381849/job/16010313648
- Fri, 18 Aug 2023 12:39:10 GMT - https://github.com/damies13/rfswarm/actions/runs/5902676509/job/16011152384
- Fri, 18 Aug 2023 12:36:47 GMT - https://github.com/damies13/rfswarm/actions/runs/5902676509/job/16011152576
- Fri, 18 Aug 2023 12:49:41 GMT - https://github.com/damies13/rfswarm/actions/runs/5902818471/job/16011537241
- Fri, 18 Aug 2023 14:10:37 GMT - https://github.com/damies13/rfswarm/actions/runs/5903588243/job/16013877110
- Fri, 18 Aug 2023 14:10:13 GMT - https://github.com/damies13/rfswarm/actions/runs/5903588243/job/16013877523
 

Times when file download succeeded:
- Fri, 18 Aug 2023 12:36:45 GMT - https://github.com/damies13/rfswarm/actions/runs/5902676509/job/16011152745
- Fri, 18 Aug 2023 12:49:35 GMT - https://github.com/damies13/rfswarm/actions/runs/5902818471/job/16011537064
- Fri, 18 Aug 2023 12:49:23 GMT - https://github.com/damies13/rfswarm/actions/runs/5902818471/job/16011537439
- Fri, 18 Aug 2023 14:11:32 GMT - https://github.com/damies13/rfswarm/actions/runs/5903588243/job/16013877323

As you can see there is often only a few seconds between a "No such host is known." error or the file being downloaded. 

I hope this is helpful in finding the issue,

Dave.

**Comment by stweil** [comment]
@damies13, that's a special case where the access was not possible most of the time because of a heavy denial of service attack which lasted more than 24 hours.
