### ISSUE TITLE
[Question] Am I doing something wrong, not getting good results?

### ISSUE THREAD

**Issue by wes-kay** [UB-Mannheim/tesseract#72]
### Your Feature Request

![ismage](https://github.com/UB-Mannheim/tesseract/assets/40011470/39def8d4-fab9-4d53-9bbe-1f921be171c2)

I've copied `tessdata_best/eng.traineddata` and replaced the in the installed `Tesseract-OCR\tessdata` directory assuming that's the only file that's needed for the "best" model. 

I run the output and, though I'm getting some pretty bad results, just want to make sure it's not something I'm missing. In the test I'm processing in gpt3, and you can see the output, but the original is pretty bad:

```
Having clear leg 14 le hardening
has proven fo be a Glginess asset

IL find I use pity hnded fiandurihg
daly 72m Jo ting down notes. en a
meeting to writhing a pergural
Letter Tv a clienl

Legit handurihog > sorlT0 |
T look fov when hiking productos

assistants

````

**Comment by stweil** [comment]
I am surprised that Tesseract could read something of that text at all. It was never trained on handwritten text and normally fails to recognize the lines of such texts. Use it only for printed text.

Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.
