### ISSUE TITLE
Send Request Error

### ISSUE THREAD

**Issue by Aditya-R-K** [UB-Mannheim/tesseract#75]
### Current Behavior

![image](https://github.com/UB-Mannheim/tesseract/assets/84246389/054ec86f-fd3c-4cee-8f8a-850d0812e8ed)

### Expected Behavior

It should Download the scripts and language data

### Suggested Fix

Please update the links in installer they are not downloading the script and language data

### tesseract -v

version 5.3.3 64 bit windows installer

### Operating System

Windows 11

### CPU

i5-83005

### Other Information

When I selected the download script and language data every time I'm getting send reqeust error as mentioned in the image

**Comment by Aditya-R-K** [comment]
I even tried by turning off all the firewalls and disabling the antivirus software, still getting same error

**Comment by stweil** [comment]
The script downloads the selected models from GitHub. Some locations don't allow direct access to GitHub. If you still have problems, I suggest to download and install the models separately.
