### ISSUE TITLE
Windows Installer: Automatically add to Path

### ISSUE THREAD

**Issue by Avasam** [UB-Mannheim/tesseract#76]
### Your Feature Request

Could the Windows installer automatically add tesseract to the Path? (`User` or `Machine` depending on whether they decided to install globally or just for themselves). It's cumbersome to have to train and support users into doing that extra step. Even a checkmark/option to add to path, just like the option to add a shortcut, would be enough.

**Comment by stweil** [comment]
No, that's not a good idea because of limitations for Windows `PATH`. Earlier installers had an option to do that. See old issues for the related problems.

The current installation installs a Windows shell link, and for that shell `PATH` is set. That should be sufficient.
