### ISSUE TITLE
New Version Available!

### ISSUE THREAD

**Issue by Dominiquini** [UB-Mannheim/tesseract#78]
### Your Feature Request

Tesseract 5.3.4 was already launched (https://github.com/tesseract-ocr/tesseract/releases/tag/5.3.4)!
Any plans to update the builds for Windows?

Thanks

**Comment by stweil** [comment]
I already created a new installer two weeks ago. Now it's uploaded.

Meanwhile there is also a 5.4.0-rc2. A build for Windows is currently running.
