### ISSUE TITLE
jpn-vert file not found

### ISSUE THREAD

**Issue by davidb1** [UB-Mannheim/tesseract#8]
Got this during installation:
![image](https://user-images.githubusercontent.com/13868996/53486276-f57fb600-3a90-11e9-89c6-6170a956474d.png)

Got the file from here: https://github.com/tesseract-ocr/tessdata/blob/master/jpn_vert.traineddata

**Comment by stweil** [comment]
That looks like a small bug in the installer: `jpn-vert` instead of `jpn_vert`. I'll fix that in the next update.

https://github.com/tesseract-ocr/tessdata_fast/raw/master/jpn_vert.traineddata is the fast variant of the model file.

**Comment by stweil** [comment]
Thank you. Fixed in commit 9dfa66bf4098c4080a7caf038480de2b0226bc55 / release [v4.1.0.20190314](https://github.com/UB-Mannheim/tesseract/releases/tag/v4.1.0.20190314).
