### ISSUE TITLE
Option for downloading Specific Language only.

### ISSUE THREAD

**Issue by Sayem-Ahmed-Shayeed** [UB-Mannheim/tesseract#80]
### Your Feature Request

i think downloading the whole package of language which one don't need is really useless and it would be better if you provide this feature of selecting specific language of one's need and download it.

**Comment by stweil** [comment]
It is already possible to select only the desired languages and scripts for the installation. What is missing?

**Comment by Sayem-Ahmed-Shayeed** [comment]
There is one
