### ISSUE TITLE
Wiki download link for 5.5.0 does not work.

### ISSUE THREAD

**Issue by jusla** [UB-Mannheim/tesseract#85]
### Current Behavior

Go to https://github.com/UB-Mannheim/tesseract/wiki
Click on the following link:
> The latest installers can be downloaded here:
> [tesseract-ocr-w64-setup-5.5.0.20241110.exe](https://github.com/tesseract-ocr/tesseract/releases/download/5.5.0/tesseract-ocr-w64-setup-5.5.0.20241110.exe) (64 bit)
A GitHub 404 page opens with the following URL: https://github.com/tesseract-ocr/tesseract/releases/download/5.5.0/tesseract-ocr-w64-setup-5.5.0.20241110.exe

### Expected Behavior

Installer is downloaded.

### Operating System

Windows 11

**Comment by stweil** [comment]
Yes, I had to remove this installer because it did not work. Now there is a new one.
